export const SET_ACTION = 'SET_ACTION';
export const SET_TOOL = 'SET_TOOL';
export const SET_SELECTED_ELEMENT = 'SET_SELECTED_ELEMENT';
export const SET_AUTH = 'SET_AUTH';
export const SET_ALL_BOARDS = 'SET_ALL_BOARDS';
export const SET_SELECTED_BOARD = 'SET_SELECTED_BOARD';